let exercises=[
        {
            url:"https://www.jefit.com/images/exercises/800_600/2912.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/2913.jpg",
            url2:"https://www.jefit.com/images/exercises/b3.jpg",
            name:"Cable Incline Press",
            mmg:"Chest",
            omg:"Shoulders",
            type:"Strength",
            machine:"Compound",
            equipment:"Bench",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/5160.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/5161.jpg",
            url2:"https://www.jefit.com/images/exercises/b3.jpg",
            name:"Stability Ball Cable One-Arm Incline Press",
            mmg:"Chest",
            omg:"Abs, Back",
            type:"Strength",
            machine:"Isolation",
            equipment:"Machine-Strength",
            difficulty:"Intermediate",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/972.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/973.jpg",
            url2:"https://www.jefit.com/images/exercises/b7.jpg",
            name:"Towel Standing Tricep Extension",
            mmg:"Triceps",
            omg:"Abs, Back",
            type:"Strength",
            machine:"Isolation",
            equipment:"Others",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/3924.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/3925.jpg",
            url2:"https://www.jefit.com/images/exercises/b0.jpg",
            name:"Abdominal Hip Roll",
            mmg:"Abs",
            omg:"Abs, Back",
            type:"Strength",
            machine:"Isolation",
            equipment:"Body Only",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/2140.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/2141.jpg",
            url2:"https://www.jefit.com/images/exercises/b0.jpg",
            name:"Triangle Pose",
            mmg:"Abs",
            omg:"Back, Upper Legs",
            type:"Strenthing",
            machine:"Compound",
            equipment:"Body Only",
            difficulty:"Intermediate",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/3140.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/3141.jpg",
            url2:"https://www.jefit.com/images/exercises/b1.jpg",
            name:"Cable Deadlift",
            mmg:"Back",
            omg:"Glutes, Upper Legs",
            type:"Strenthing",
            machine:"Isolation",
            equipment:"Machine-Strength",
            difficulty:"Intermediate",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/2496.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/2497.jpg",
            url2:"https://www.jefit.com/images/exercises/b0.jpg",
            name:"Dumbbell Alternating Cobra on Stability Ball",
            mmg:"Abs",
            omg:"Back, Shoulders",
            type:"Strength",
            machine:"Isolation",
            equipment:"Dumbbell",
            difficulty:"Intermediate",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/3728.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/3729.jpg",
            url2:"https://www.jefit.com/images/exercises/b8.jpg",
            name:"Seated Hamstring and Calf Stretch",
            mmg:"Upper Legs",
            omg:"Back, Shoulders",
            type:"Stretching",
            machine:"N/A",
            equipment:"Bands",
            difficulty:"Intermediate",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/3284.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/3285.jpg",
            url2:"https://www.jefit.com/images/exercises/b1.jpg",
            name:"Barbell Prone Cambered Row",
            mmg:"Back",
            omg:"Biceps, Shoulders",
            type:"Strength",
            machine:"Isolation",
            equipment:"Barbell",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/2360.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/2360.jpg",
            url2:"https://www.jefit.com/images/exercises/b0.jpg",
            name:"Knee Draw In",
            mmg:"Abs",
            omg:"Back, Glutes",
            type:"Strength",
            machine:"Compound",
            equipment:"Body Only",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/3552.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/3553.jpg",
            url2:"https://www.jefit.com/images/exercises/b7.jpg",
            name:"Pin Press",
            mmg:"Triceps",
            omg:"Chest, Forearm",
            type:"Powerlifting",
            machine:"Compound",
            equipment:"Barbell",
            difficulty:"Intermediate",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/892.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/893.jpg",
            url2:"https://www.jefit.com/images/exercises/b7.jpg",
            name:"EZ Bar Decline Close Grip Skull Crusher",
            mmg:"Triceps",
            omg:"Chest, Shoulders",
            type:"Strength",
            machine:"Isolation",
            equipment:"EZ Curl Bar",
            difficulty:"Intermediate",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/2752.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/2753.jpg",
            url2:"https://www.jefit.com/images/exercises/b0.jpg",
            name:"Stability Ball Roman Twist",
            mmg:"Abs",
            omg:"Chest, Shoulders",
            type:"Strength",
            machine:"Isolation",
            equipment:"Exercise Ball",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/5288.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/5289.jpg",
            url2:"https://www.jefit.com/images/exercises/b6.jpg",
            name:"Dumbbell Front Hammer Raise",
            mmg:"Shoulders",
            omg:"Chest, Shoulders",
            type:"Strength",
            machine:"Isolation",
            equipment:"Dumbbell",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/3744.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/3745.jpg",
            url2:"https://www.jefit.com/images/exercises/b8.jpg",
            name:"Single-Leg Push-Off",
            mmg:"Upper Legs",
            omg:"Lower Legs, Shoulders",
            type:"Strength",
            machine:"Compound",
            equipment:"Others",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/3508.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/3509.jpg",
            url2:"https://www.jefit.com/images/exercises/b6.jpg",
            name:"Dumbbell Shoulder Abduction",
            mmg:"Shoulders",
            omg:" Lower Legs, Shoulders",
            type:"Strength",
            machine:"Isolation",
            equipment:"Dumbbell",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/2976.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/2977.jpg",
            url2:"https://www.jefit.com/images/exercises/b0.jpg",
            name:"Cable Wood Chop",
            mmg:"Abs",
            omg:"Lower Legs, Shoulders",
            type:"Strength",
            machine:"Isolation",
            equipment:"Machine-Strength",
            difficulty:"Beginner",
        },
        {
            url:"https://www.jefit.com/images/exercises/800_600/56.jpg",
            url1:"https://www.jefit.com/images/exercises/800_600/57.jpg",
            url2:"https://www.jefit.com/images/exercises/b3.jpg",
            name:"Cable High Cross-Over",
            mmg:"Chest",
            omg:"Triceps, Shoulders",
            type:"Strength",
            machine:"Isolation",
            equipment:"Machine-Strength",
            difficulty:"Beginner",
        },
    
    ]

export default exercises;